"""baseline: urls table

Revision ID: 3813da2d7b76
Revises: 
Create Date: 2026-08-29 16:36:33.222614

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3813da2d7b76'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
