"""add expires_at, user_id, is_active

Revision ID: cd8736f28600
Revises: 3813da2d7b76
Create Date: 2026-08-29 17:52:41.060435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8736f28600'
down_revision: Union[str, Sequence[str], None] = '3813da2d7b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('urls', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_active')
    op.drop_column('urls', 'user_id')
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
