"""add deleted_at to urls

Revision ID: ff8ab26cc6ea
Revises: cd8736f28600
Create Date: 2026-08-31 18:45:46.182717

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff8ab26cc6ea'
down_revision: str | Sequence[str] | None = 'cd8736f28600'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'deleted_at')
    # ### end Alembic commands ###
